FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy the project files and restore dependencies
COPY SOCData/SOCData.sqlproj SOCData/
COPY SOCMobile/SOCMobile.csproj SOCMobile/
COPY SOCApi/SOCApi.csproj SOCApi/
COPY SOCWeb/SOCWeb.esproj SOCWeb/
RUN dotnet restore

# Copy the rest of the files and build the projects
COPY . ./
RUN dotnet publish -c Release -o out

# Build the final image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .

# Set environment variables
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

# Start the application

ENTRYPOINT ["dotnet", "SOCWeb.dll"]